name: Snyk Security Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install Snyk
        run: npm install -g snyk
      
      - name: Authenticate with Snyk
        run: snyk auth $SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Verificar archivos del directorio
        run: ls -la
      
      - name: Run Snyk Code to check for vulnerabilities
        run: snyk code test --severity-threshold=high
        continue-on-error: true
      
      - name: Monitor project in Snyk Dashboard
        run: snyk monitor

