name: Snyk Security Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install Snyk
        run: npm install -g snyk
      
      - name: Verificar archivos del directorio
        run: ls -la
      
      # Usar Snyk Code para analizar el código fuente (no dependencias)
      - name: Run Snyk Code to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test --severity-threshold=high
        continue-on-error: true
      
      # Opcional: Analizar contenedores Docker si los usas
      - name: Run Snyk to check Docker
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          if [ -f "Dockerfile" ]; then
            snyk container test $(docker build -q .)
          fi
        continue-on-error: true
