name: Snyk Security Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install Snyk
        run: npm install -g snyk
      
      - name: Verificar archivos del directorio
        run: ls -la

      # Analizar código fuente con Snyk Code
      - name: Run Snyk Code to check for vulnerabilities
        run: snyk code test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      # Subir resultados al dashboard de Snyk
      - name: Monitor project in Snyk Dashboard
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Opcional: Analizar contenedores Docker si los usas
      - name: Run Snyk to check Docker
        run: |
          if [ -f "Dockerfile" ]; then
            docker build -t myapp:latest .
            snyk container test myapp:latest
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

